name: Sync Docker Images
on:
  schedule:
  - cron: "0 0 * * *" # Run every day
  push:
    branches:
    - main
    - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: sync multus-cni
      uses: titenkov/docker-sync-action@v1
      with:
        source: ghcr.io/k8snetworkplumbingwg/multus-cni
        destination: zengxu
        destination-credentials: zengxu:${{ secrets.DOCKERHUB_TOKEN }}
    - name: sync calico operator
      uses: titenkov/docker-sync-action@v1
      with:
        source: quay.io/tigera/operator
        destination: docker.io/zengxu/tigera-operator
        destination-credentials: zengxu:${{ secrets.DOCKERHUB_TOKEN }}
        versions: |
          v1.30.4