name: Sync Docker Images
on:
  schedule:
  - cron: "0 0 * * *" # Run every day
  push:
    branches:
    - main
    - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: sync multus-cni
      uses: titenkov/docker-sync-action@v1
      with:
        source: ghcr.io/k8snetworkplumbingwg/multus-cni
        destination: zengxu
        destination-credentials: zengxu:${{ secrets.DOCKERHUB_TOKEN }}
    - name: sync acorn-io
      uses: titenkov/docker-sync-action@v1
      with:
        source: ghcr.io/acorn-io/acorn
        destination: zengxu
        destination-credentials: zengxu:${{ secrets.DOCKERHUB_TOKEN }}
    - name: sync calico operator # titenkov/docker-sync-action is suitable for a whole repo, but sometimes not for single tag
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: quay.io/tigera/operator:v1.30.4
        target_repository: docker.io/zengxu/tigera-operator:v1.30.4
        target_username: zengxu
        target_password: ${{ secrets.DOCKERHUB_TOKEN }}
